### ISSUE TITLE
[BUG] Standings W-L Issue

### ISSUE THREAD

**Issue by troyschmid41** [nmelhado/league-page#179] opened 2022-12-01 17:32 UTC
**Describe the bug**
The standings tab doesn't seem to populate the W-L records correctly to each team.  It looks like the values are correct but not assigned to the proper manager. 

**Your League ID**
866130738192539648

**To Reproduce**
1. Go to 'League Info/Managers'
2. Look at W-L records

**Expected behavior**
Correct W-L assigned to proper manager.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**

**Comment by troyschmid41** [comment] 2022-12-01 17:34
The power rankings graph and the managers tab also do not seem to align.

**Comment by nmelhado** [comment] 2022-12-01 17:39
Do you mind posting some screenshots of the mismatch and your league's website?

**Comment by troyschmid41** [comment] 2022-12-01 17:41
![managers](https://user-images.githubusercontent.com/119614365/205122839-40deb4d3-0ce2-4dd9-916b-1991a906ea2a.jpg)
![standings](https://user-images.githubusercontent.com/119614365/205122843-3c8c2ee8-87e6-4be9-b624-a820e4e28101.jpg)
![standingsSleeper](https://user-images.githubusercontent.com/119614365/205122845-608753b4-eea2-4738-b4c9-8851c427e04f.jpg)

**Comment by troyschmid41** [comment] 2022-12-01 17:42
I also added the managers tab as they don't seem to align with the power rankings order.

**Comment by lrtoenjes** [comment] 2023-01-02 19:24
I have this problem too and after some debugging, I believe the `rostersStore` is not remaining sorted by `roster_id`. Initially, the "Standings" page is correct, as is the "Managers" page. However, I can reproduce the bug by going to the "Drafts" page and then back to the "Standings" page, and that's when the "Standings" has the manager's incorrectly ordered but the records of W-L correct. I have no Svelte experience, but it seemed me that despite `processRosters()` in `leagueRosters.js` sorting the rosters by `roster_id`, the array did not remain sorted when `getLeagueRosters()` was called in the `leagueDrafts.js` file.

**Comment by nmelhado** [comment] 2023-01-08 14:08
I have an update coming out (https://github.com/nmelhado/league-page/issues/181) that I believe fixes this just due to revised implementation. I'm hoping to release it within the next week or two.

**Comment by lrtoenjes** [comment] 2023-01-14 05:17
@nmelhado I synched the change from #185 into my repo and was still able to reproduce this bug by following the steps in my previous comment. For the time being, I've implemented a small change to the `leagueRosters.js` utility so that subsequent calls to `getLeagueRosters()` always returns a sorted `rosters` array. As stated before, I noticed that the first call to `getLeagueRosters()` would return a sorted array, but every call after that, would return the unsorted array from the store.

**Comment by nmelhado** [comment] 2023-01-14 14:00
Ah ok, I was hoping it was fixed due to how team names are being shown. I'll work on a fix for this. Seems like the sort is a little brittle, so I might just move away from that and turn rosters into an object. Might be slightly more work, but it should prevent similar issues from happening again.

**Closed** 2023-01-15 02:07 UTC
Labels: bug, good first issue

**Comment by nmelhado** [comment] 2023-01-15 02:10
@lrtoenjes this should actually fix it. Sorry for the false fix the first time. If there are still issues, let me know!
