### ISSUE TITLE
[SLEEPER_BUG][ONGOING] Sleeper's data is messed up and is messing with records data

### ISSUE THREAD

**Issue by dopiedopeman** [nmelhado/league-page#193] opened 2023-01-17 15:45 UTC
**Describe the bug**
Wrong Data in Record page. For example a manager got 7.70 Points in "All-Time Single Week Scoring Lows" - originaly it was more 70 Points.

**Your League ID**
708330202568126464

**Expected behavior**
Original Points from historic and actual league.

**Screenshots**
![image](https://user-images.githubusercontent.com/120254237/212943606-f1bad7ae-e1a7-4022-a535-184bbb88f924.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 108

**Smartphone (please complete the following information):**
 - Device: Iphone 12 Pro
 - OS: iOS16.2
 - Browser safari

**Comment by nmelhado** [comment] 2023-01-17 16:23
Unfortunately, this isn't a bug on league page's end 😕. Sleeper has a bug and it's data is a mess. If you look on the app at previous seasons/weeks you'll see a bunch of missing data. Since the issue is on their end, there's nothing I can do until they fix it.

**Comment by nmelhado** [comment] 2023-01-17 16:28
If/when Sleeper fixes this, I'll delete update here and delete the issue.

**Comment by lrtoenjes** [comment] 2023-01-25 04:07
I noticed that the Sleeper API isn't properly accounting for points accrued in a matchup from a player that is no longer on your team since that matchup. I feel like this bug in their data/algorithms is new because I don't recall this happening before when I looked back at previous matchups last season...

**Comment by nmelhado** [comment] 2023-01-25 18:02
Yup, if everyone could help report it on the Sleeper app, it should increase the severity of the issue and encourage them to resolve it more quickly. It's definitely frustrating, because it's completely messing up the rankings pages.

**Comment by nmelhado** [comment] 2023-02-16 16:41
I think this is fixed. If anyone else can confirm everything looks good for their league as well, I'll close this.

**Comment by lrtoenjes** [comment] 2023-02-16 20:32
It looks like it is fixed. My "off roster" players  are now being credited with points in matchups in the weeks before I traded them.

**Closed** 2023-02-21 15:57 UTC
Labels: sleeper bug
