### ISSUE TITLE
Multiple issues after merging to forked repo

### ISSUE THREAD

**Issue by HansPeterOrding** [nmelhado/league-page#96] opened 2021-11-24 15:35 UTC
**Describe the bug**
After merging new changes (> 26.8.2021) to existing pages, some things don't work as expected anymore. The following problems can be viewed here:
https://deepsleeper.upsidebowl.upsidefantasy.de/

Issues found:

Homepage:
* Multiple "undefined" values in Recent Waiver Moves view
* Rest of season rankings broken

Matchups:
* Matchup do not show

Trades & Waivers:
* Multiple undefined values in view

League Info - Standings:
* As the league has no divisions, the corresponding columns are obsolete
* The league has "Extra game each week against league median" activated in league settings. The median games are not considered in the W|T|L columns, so the standings are basically wrong.

Resources:
* Javascript error loading news

**Your League ID**
739519802820984832

**To Reproduce**
1. https://deepsleeper.upsidebowl.upsidefantasy.de/
2. Click the mentioned areas
3. See error

**Comment by nmelhado** [comment] 2021-12-10 17:20
When I visit that page for the first time (or in incognito) I'm finding the same errors you describe. On a reload, they seem to go away. It most likely is being caused during the cache steps, so that when there is no data, the error occurs. I'm going to look into this when I finish merging the open PRs

**Comment by nmelhado** [comment] 2022-01-03 16:07
I was unable to reproduce this locally. I can reproduce this when I visit your link above, but not locally when I use the supplied league ID. Is it possible you edited any of the relevant code and that has created a bug? If not, could you debug locally and supply the console errors?

**Comment by nmelhado** [comment] 2022-01-13 18:14
Since I can't reproduce this locally, I'm going to close this. If you have any extra info that can help me reproduce the behavior, feel free to reopen it.

**Closed by nmelhado** 2022-01-13 18:14 UTC
Labels: bug
